### ISSUE TITLE
Unexpected diagonal format with `testcases/gaxe2_axbattler_01_input.png`

### ISSUE THREAD

**Issue by sebastien** [vvanirudh/Pixel-Art#4]
The test case `testcases/gaxe2_axbattler_01_input.png` fails on Ubuntu 17.04 with Python 2.7.13.

```
ython main.py 
Please Enter the name of the png file (with extension)testcases/gaxe2_axbattler_01_input.png
graph done
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    main()
  File "main.py", line 9, in main
    process_file(filename)
  File "main.py", line 16, in process_file
    data.depixelize()
  File "/home/sebastien/Desktop/Pixel-Art/algorithm.py", line 40, in depixelize
    self.remove_diagonals()
  File "/home/sebastien/Desktop/Pixel-Art/algorithm.py", line 127, in remove_diagonals
    assert False, "Unexpected diagonal format"
```

**Comment by vvanirudh** [comment]
I am sorry but its been ages since we ran the code and I can't give time to debug this.

I hope you found a way to resolve it. Sorry.
