### ISSUE TITLE
Does not support alpha channel

### ISSUE THREAD

**Issue by waptaff** [vvanirudh/Pixel-Art#5]
When trying to vectorize a 1-bit PNG image with an alpha channel (e.g. pixels are either black or transparent), program chokes with:

```
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    main()
  File "main.py", line 9, in main
    process_file(filename)
  File "main.py", line 12, in process_file
    data = PixelData(read_png(filename))
  File "/home/wayne/src/pixelart/Pixel-Art/input.py", line 4, in read_png
    width, height, pixels, metadata = png.Reader(filename = filename).asRGB8() # Get the pixel data as RGB with 8 bits each
  File "/usr/lib/python2.7/site-packages/png.py", line 2171, in asRGB8
    return self._as_rescale(self.asRGB, 8)
  File "/usr/lib/python2.7/site-packages/png.py", line 2139, in _as_rescale
    width,height,pixels,meta = get()
  File "/usr/lib/python2.7/site-packages/png.py", line 2199, in asRGB
    raise Error("will not convert image with alpha channel to RGB")
png.Error: Error: will not convert image with alpha channel to RGB
```

Example image:
![pixelart-alpha](https://user-images.githubusercontent.com/6563434/33377057-139e7f96-d4de-11e7-856e-a50ec078c1e7.png)

**Comment by vvanirudh** [comment]
We did not implement this considering alpha channels as an input. You are welcome to extend the code and send in a pull request. Unfortunately, I cannot allocate time for that myself.
